### ISSUE TITLE
Runtime error running rollout script from the README

### ISSUE THREAD

**Issue by afnanmmir** [ARISE-Initiative/robosuite-benchmark#12]
I am currently attempting to run the robosuite benchmark on Ubuntu 20.04 with mujoco-py version 2.0.2.13 and numpy version 1.21.0.
Whenever I attempt to run the rollout script from the readme, I am met with this error message. Does anyone know a fix to this?

Error:
Traceback (most recent call last):
  File "scripts/rollout.py", line 87, in <module>
    reward_shaping=True
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/base.py", line 41, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/manipulation/door.py", line 184, in __init__
    camera_depths=camera_depths,
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 168, in __init__
    robot_configs=robot_configs,
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/robot_env.py", line 196, in __init__
    hard_reset=hard_reset,
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/base.py", line 147, in __init__
    self._reset_internal()
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/manipulation/door.py", line 375, in _reset_internal
    super()._reset_internal()
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/environments/robot_env.py", line 400, in _reset_internal
    robot.reset(deterministic=self.deterministic_reset)
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/robots/single_arm.py", line 175, in reset
    super().reset(deterministic)
  File "/home/afnanmir/miniconda3/envs/rb_bench/lib/python3.7/site-packages/robosuite/robots/robot.py", line 147, in reset
    self.base_ori = T.mat2quat(self.sim.data.get_body_xmat(self.robot_model.root_body).reshape((3, 3)))
TypeError: expected dtype object, got 'numpy.dtype[float32]'

**Comment by humphreyde** [comment]
it's wrong with numba
