### ISSUE TITLE
issues for ruunning train.py with TD3

### ISSUE THREAD

**Issue by faker52** [ARISE-Initiative/robosuite-benchmark#22]
nohup: ignoring input
[robosuite WARNING] No private macro file found! (__init__.py:7)
[robosuite WARNING] It is recommended to use a private macro file (__init__.py:8)
[robosuite WARNING] To setup, run: python /home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/robosuite/scripts/setup_macros.py (__init__.py:9)
No personal conf_private.py found.
doodad not detected

------------- Running TD3 --------------
  Params: 
    variant: scripts/variantTD3Pnp.json

2023-11-07 18:43:56.892015 CST | Variant:
2023-11-07 18:43:56.892349 CST | {
  "algorithm": "TD3",
  "algorithm_kwargs": {
    "batch_size": 128,
    "eval_max_path_length": 500,
    "expl_max_path_length": 500,
    "min_num_steps_before_training": 3300,
    "num_epochs": 2000,
    "num_eval_steps_per_epoch": 2500,
    "num_expl_steps_per_train_loop": 2500,
    "num_trains_per_train_loop": 1000
  },
  "eval_environment_kwargs": {
    "control_freq": 20,
    "controller": "OSC_POSE",
    "env_name": "Lift",
    "hard_reset": false,
    "horizon": 500,
    "ignore_done": true,
    "reward_scale": 1.0,
    "robots": "['Panda']"
  },
  "expl_environment_kwargs": {
    "control_freq": 20,
    "controller": "OSC_POSE",
    "env_name": "PickPlaceCan",
    "hard_reset": false,
    "horizon": 500,
    "ignore_done": true,
    "reward_scale": 1.0,
    "robots": "['Panda']"
  },
  "policy_kwargs": {
    "hidden_sizes": [
      256,
      256
    ]
  },
  "qf_kwargs": {
    "hidden_sizes": [
      256,
      256
    ]
  },
  "replay_buffer_size": 1000000,
  "seed": 17,
  "trainer_kwargs": {
    "discount": 0.99,
    "reward_scale": 1.0
  },
  "version": "normal"
}
/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Traceback (most recent call last):
  File "scripts/train.py", line 131, in <module>
    run_experiment()
  File "scripts/train.py", line 104, in run_experiment
    experiment(variant, agent=args.agent)
  File "/data1/qxx/RL/Change-maple/bseline/robosuite-benchmark/util/rlkit_utils.py", line 163, in experiment
    algorithm.train()
  File "/data1/qxx/RL/Change-maple/bseline/robosuite-benchmark/util/rlkit_custom.py", line 46, in train
    self._train()
  File "/data1/qxx/RL/Change-maple/bseline/robosuite-benchmark/util/rlkit_custom.py", line 213, in _train
    self.eval_data_collector.collect_new_paths(
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/samplers/data_collector/path_collector.py", line 42, in collect_new_paths
    path = rollout(
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/samplers/rollout_functions.py", line 112, in rollout
    a, agent_info = agent.get_action(o)
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/torch/networks.py", line 111, in get_action
    actions = self.get_actions(obs_np[None])
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/torch/networks.py", line 115, in get_actions
    return eval_np(self, obs)
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/torch/core.py", line 18, in eval_np
    outputs = module(*torch_args, **torch_kwargs)
  File "/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/torch/networks.py", line 108, in forward
    return super().forward(obs, **kwargs)
  File "/data1/qxx/RL/Change-maple/bseline/rlkit/rlkit/torch/networks.py", line 69, in forward
    h = fc(h)
  File "/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qxx/anaconda3/envs/robosuite/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x42 and 46x256)

**Comment by amandlek** [comment]
We need more information to reproduce the issue. Can you give us the precise training command, config being used, and information on the dataset?
